version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: diary
      POSTGRES_USER: diary_user
      POSTGRES_PASSWORD: diary_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: